version: "3.0"

services:
  postgres:
    image: postgres:9.6.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=8neEmdvl
    volumes:
      - ./docker-persistence/postgres:/var/lib/postgresql/data

  firehol-ip-aggregator:
    image: python:3.6.2-alpine3.6
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - ./docker-persistence/app-data/git_data:/app/git_data
    entrypoint: /app/entrypoint.sh hug -f modules/api.py
    depends_on:
      - postgres
