version: "2.0"

services:
  postgres:
    image: postgres:9.6.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=8neEmdvl
    volumes:
      - ./docker-persistence/postgres:/var/lib/postgresql/data

  firehol-ip-aggregator:
    build: .
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./docker-persistence/app-data/git-data:/app/git-data
      - ./docker-persistence/config.json:/app/conf/config.json
    depends_on:
      - postgres
